export * from './checkdigit/historical.scopes';
export declare enum CheckdigitScopes {
    Buyer = "Buyer",
    Company = "Company",
    PlaidItem = "PlaidItem",
    BalanceCheck = "BalanceCheck",
    Supplier = "Supplier",
    DivisionRelationship = "DivisionRelationship",
    TermsChoice = "TermsChoice",
    ShopifyCredential = "ShopifyCredential",
    WoocommerceCredential = "WoocommerceCredential",
    BigcommerceCredential = "BigcommerceCredential",
    TradegeckoCredential = "TradegeckoCredential",
    Workflow = "Workflow",
    AuditEntry = "AuditEntry",
    DisposedEvent = "DisposedEvent",
    PendingEvent = "PendingEvent",
    BuyerApplication = "BuyerApplication",
    AchFile = "AchFile",
    AchGateway = "AchGateway",
    BankAccount = "BankAccount",
    BankTransaction = "BankTransaction",
    Batch = "Batch",
    OrderReference = "OrderReference",
    PaymentRequest = "PaymentRequest"
}
